/**
 * @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'.DS_Store',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'ckeditor.iml',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		a11yhelp: 1,
		about: 1,
		basicstyles: 1,
		bidi: 1,
		blockquote: 1,
		button: 1,
		clipboard: 1,
		codemirror: 1,
		codesnippet: 1,
		colorbutton: 1,
		colordialog: 1,
		contextmenu: 1,
		dialog: 1,
		dialogadvtab: 1,
		dialogui: 1,
		div: 1,
		divarea: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		fakeobjects: 1,
		filebrowser: 1,
		find: 1,
		floatingspace: 1,
		floatpanel: 1,
		font: 1,
		format: 1,
		forms: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		iframe: 1,
		image: 1,
		image2: 1,
		indent: 1,
		indentlist: 1,
		indentblock: 1,
		justify: 1,
		language: 1,
		link: 1,
		list: 1,
		listblock: 1,
		liststyle: 1,
		magicline: 1,
		mathjax: 1,
		maximize: 1,
		menu: 1,
		menubutton: 1,
		pagebreak: 1,
		panel: 1,
		panelbutton: 1,
		pastefromword: 1,
		pastetext: 1,
		placeholder: 1,
		popup: 1,
		removeformat: 1,
		resize: 1,
		richcombo: 1,
		selectall: 1,
		showblocks: 1,
		showborders: 1,
		smiley: 1,
		sourcearea: 1,
		specialchar: 1,
		stylescombo: 1,
		tab: 1,
		table: 1,
		tableresize: 1,
		tabletools: 1,
		templates: 1,
		textselection: 1,
		toolbar: 1,
		undo: 1,
		widget: 1,
		wordcount: 1,
		wysiwygarea: 1,
		youtube: 1
	},
    languages : {
		'de' : 1,
		'en' : 1,
		'fr' : 1,
		'it' : 1,
		'nl' : 1
	}
};
